### PR TITLE
post-abandonment: user-defined keyring overrides

### PR DESCRIPTION
**Pull request by codeofdusk**
As part of my post-abandonment patches, these changes allow the user to override any key in the keyring. A custom Twitter API key/secret option has been added to the UI.

### CODE REVIEW

**Comment by manuelcortez** [comment]
It seems you're lost a bit. At the end of the last year, the company where I do work has decided to pay me for developing some projects, one of these projects is TWBlue. I am working in making the client more independent of the official server, that's the reason why i decided to merge your commit about disabling check for updates at startup, but I no have plans about abandonment or discontinue the project. In particular, I won't merge this commit because we would return to these days, where people just change this API key/secret, and "Oh! I have a new twitter client" but based in the same source code. We'll have dozens of clones of the same source code, as happened with the qube when they allowed to everyone to do the same.

**Comment by codeofdusk** [comment]
No, this is a user-defined setting.
I already allow people to use a custom API key/secret by editing application.py (added that feature a long time ago).
It doesn’t modify the program itself, just the user’s settings.

Bill

**Comment by codeofdusk** [comment]
Thanks for the update, I read your blog post a few months ago so thought you had left the client to José.

Bill

**Comment by manuelcortez** [comment]
Yea, I understand your viewpoint, but we shouldn't allow that for a reason. For the twitter platform, you are using a completely different client if you just change the secrets of the application (in fact I shouldn't add even the libraries that contains the keys in the sources, only instructions on how to do that). Because we are not creating a framework for developers who want to create their own clients, we are creating a full application, wich shouldn't be different for twitter. I am working in something to do when twitter blocks TWBlue or something like that, but it will not require to everyone to change secrets. Of course developers still will be able to change their secrets, but they will do it at their own risks.

**Pull request closed without merging**
