### PR TITLE
Make several modifications for better running from source

### PR DESCRIPTION
**Pull request by Menelion**
* Added a requirements file for easier dependencies installation;
* Updated Gitignore to add VLC libraries (see #243);
* Updated the Readme file to reflect these changes.

### CODE REVIEW

**Comment by jmdaweb** [comment]
Hello.
Can you specify in the readme a method to update all installed packages and their dependencies? That information is missing when switching from setuptools to pip.

**Comment by Menelion** [comment]
@jmdaweb, do you mean `pip install --upgrade`?

**Comment by jmdaweb** [comment]
Yes. In requirements.txt, you must have into account all dependencies, not only the top-level ones (future, futures, oauthlib, etc.). TWBlue will be more robust and stable if the sub-dependencies are also updated.
I have one question: why do you prefer pip over easy_install? The last one stores the packages in separate folders, and makes easier some tasks.
Regarding running from source and vlc: you don't have to copy anything to the src directory. If we take a look to the python-vlc module, it expects in first place two environment variables: 

* PYTHON_VLC_LIB_PATH: full path to libvlc.dll
* PYTHON_VLC_MODULE_PATH: path to vlc plugins directory.

You can set these variables by going to system properties, or wait some minutes until I finish testing changes and commit the result. The related code is as follows:

```
  if system=="Windows":
   arch="x86"
   if platform.architecture()[0][:2] == "64":
    arch="x64"
   os.environ['PYTHON_VLC_MODULE_PATH']=paths.app_path("..", "windows-dependencies", arch, "plugins")
   os.environ['PYTHON_VLC_LIB_PATH']=paths.app_path("..", "windows-dependencies", arch, "libvlc.dll")
```

These variables don't need to be set on binary versions because libvlc.dll and plugins directory are inside the application folder.
Regards.

**Comment by Menelion** [comment]
@jmdaweb, so my PR is invalid at this point? As for Pip, oh well... it seems a really widespread practice to do that, am I wrong?

**Comment by Menelion** [comment]
I'm actually right, Pip is recommended, see [this StackOverflow answer](https://stackoverflow.com/a/30408520/).

**Comment by jmdaweb** [comment]
No. Pip was recommended 3 years ago, when the question was created. Nowadays easy_install can install wheel and binary packages (i can install and update WXPython, for example). TWBlue does not need virtual environments or uninstalling anything. However, requirements.txt is an advantage not only for users, but for us too. Thush, regarding this pull request:

* .gitignore changes can be safely reverted. In the latest commit vlc media player is loaded from the windows-dependencies folder, so there is no need to copy files.
* Readme file: provide a way to update installed packages. Reword the line talking about vlc. All the remaining changes (specially the markdown fixes) are welcome.
* requirements.txt: add all the dependencies. Get them from this line on our readme file:
easy_install -Z --upgrade wxpython six configobj markdown future requests oauthlib requests-oauthlib requests-toolbelt pypubsub==3.3.0 pygeocoder arrow python-dateutil futures winpaths PySocks win_inet_pton yandex.translate idna chardet urllib3 youtube-dl python-vlc

Once you commit these changes, and if @manuelcortez agrees, the pull request will be merged.
Regards.

**Comment by manuelcortez** [comment]
Hello,
I thought PIP is still the most accepted option when talkin about python package installation, though in TWBlue we never use anything advanced so we can go well with easy_install. Personally I prefer pip. @Menelion, I can merge the pr and fix @jmdaweb's suggestion if needed.

**Comment by Menelion** [comment]
@jmdaweb, @manuelcortez, it seems, I fixed it. And I also squashed the commits to make the history cleaner. Thanks!

**Pull request merged**
