### PR TITLE
WXPython: Move to Project Phoenix

### PR DESCRIPTION
**Pull request by codeofdusk**
This pull request ports TWBlue to the new Project Phoenix version of WXPython; a complete rewrite which is now the actively maintained version. While no official release has been made yet, many projects have migrated already and the new library is considered stable by the developers. Additionally, the library is compatible with Python 3.x so would ease Python 3 migration. While the client is functional, some deprecated methods and classes may still be used; testers should look for deprecation warnings in the logs so we can fix them before they are removed.

### CODE REVIEW

**Comment by codeofdusk** [comment]
I created [a pull request](http://github.com/jmdaweb/twblue_deps_windows/pull/1) which should be merged after this one.

**Comment by manuelcortez** [comment]
Thanks! Will check it this weekend. Have you tried to build something with Py2exe?

**Comment by codeofdusk** [comment]
Not yet: these pull requests are actually part of a bigger effort to migrate the project to Python 3.

As part of that, I’m going to switch out py2exe for Pyinstaller since it tends to generate smaller executables and has better py3 support.


Bill

**Comment by codeofdusk** [comment]
Please merge the pull requests I’ve sent you as soon as you can, they’re dependencies of the pull request that switches us to py3.

 

Thanks,

Bill

**Comment by manuelcortez** [comment]
This has been merged for now in the [py3](https://github.com/manuelcortez/TWBlue/tree/py3) branch. There we'll fix stuff and prepare code for migrating to python 3. Once everything works fine in Py3 we can move that code into the base branch.

**Comment by codeofdusk** [comment]
I have my own py3 branch as well. Perhaps I should send you a separate pr to merge them?

Thanks,
Bill

**Pull request closed without merging**
