### PR TITLE
Created release.yml - action file for automated release on push.

### PR DESCRIPTION
**Pull request by Arfs6**
Implemented github workflow that creates a new TWBlue release on github.

### Github Issues

This pull request addresses the following issues:

1. [github workflow for releases](https://github.com/MCV-Software/TWBlue/issues/561)
2. [Releases section is not up-to-date](https://github.com/MCV-Software/TWBlue/issues/558)

#### Edited Files

1. `scripts/twblue.nsi`: Dropped support for 32 bit in installer as discussed in #561. Now TWBlue displays an error message to a user trying to use the installer on 32 bit and aborts the installation process.

#### New Files

1. `.github/workflows/release.yml`: Workflow yaml for creating new github release. This work flow runs on each push to the next-gen branch. It builds a new installer for TWBlue and creates a new snapshot release with the newly built installer as an asset.
2. `scripts/build.ps1`: A powershell script for building binary of twblue. The release.yml workflow file uses this to build the x64 binary.

### Notes

1. CX_Freeze shows a warning when building the binary on the workflow runner. According to the answer to this [question](https://social.msdn.microsoft.com/Forums/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls) asked on microsoft forum, those dlls are meant to be implementation details and aren't supposed to be packaged with the executable.
2. For testing purposes, I created a new [repo](https://github.com/arfs6/testing_actions) with the content of this repo. If you visit the [releases page](https://github.com/Arfs6/testing_actions/releases), you'll see a new snapshot installer for TWBlue. For a successful run of the action, visit <https://github.com/Arfs6/testing_actions/actions/runs/7357484890>.

### CODE REVIEW

**Comment by manuelcortez** [comment]
Hi, this looks super awesome! Do you think you could change it so it generates a release whenever we push new tags to next-gen? It would allow us to have more control about the time for a new release. Also, if you could enable the workflow for being triggered manually from the actions page it would be perfect. I haven't seen the code yet, so if this is already done, ignore this please.

**Comment by manuelcortez** [comment]
Sorry for the new request, but do you think you can upload a zip version of the dist files, so we can distribute it as a portable version? If you can't / dohn't have time it's Okay, I can do this tomorrow or so.

**Comment by Arfs6** [comment]
Hi. I didn't mentioned this, but the current version creates a snapshot release. OH... something just came to my mind. The python files that generates the version of TWBlue has no idea it's a snapshot release. With this in mind, do you think having more control over when the snapshot release is created is still usefull? To reiterate, here are the things you'd want me to work on:
1. Make workflow to run when a new tag is pushed.
2. Enable manual triggering of action. This could be used for stable released as it requires more info like change log and what's new.
3. Zip the dist directory and add it to the assets.
How do you suggest tweaking the version to show it's a snapshot?
Initially, I was thinking of working on the snapshot release first and then doing the stable release later.

**Comment by Arfs6** [comment]
To implement the stable release, I need to figure out the following:
1. How change log is generated. Automatically or manually?
2. What the updater requires in order to update the app.
3. How to manage previous releases. For the snapshots, previous releases are just overridden. This doesn't make sense for the stable release. I think this is the part that would need manual intervention.

**Comment by manuelcortez** [comment]
Since this year, when we've started to version TWBlue as year.month.day, we no longer use snapshot releases. During first years of TWBlue development this idea of having both snapshot and stable versions made a lot of sense, because there might be times where we wanted to ship new ideas, but those ideas might break client's base features for people. Lately, TWBlue's codebase has been quite stable in the sense that it is very rare to break something important and, due to CI deployments, even if we break something, it'd be just a matter of pushing a new tag and wait for the release to appear in the site. So here is what I consider we'd need to implement in order to have a release process completely done in github actions:

1. Generate version info for every new release. I think you could use the tag name withing github actions (we name tags like 2023.12.29). Additionally, there's a file within the src directory called write_version_info.py, which will retrieve the date of the last pushed commit on GitLab and append the date of generated commit to application.py as version. You could adapt this to retrieve the commit from GitHub and call this file from the workflow. It's completely up to you.
2. Changelog is generated manually (every time there is a new feature or bugfix, I try to update changelog) and lives as a markdown document in the doc folder.
3. As we have only one kind of versions, I think we could avoid overriding the latest version and keep a release history in case it'd be needed.
4. Updates are retrieved against the json update file. You have an example in the repo, at updates/updates.json. I'll modify TWBlue soon to look only in this location (right now it looks first in the TWBlue website, second in this location, but I'll move TWBlue to twblue.github.io and stop the twblue.es domain, as it looks more community oriented to me).

Please do let me know if you have any more questions regarding this process. I'll be glad to help even with some of those tasks if you don't have enough time.

**Comment by jmdaweb** [comment]
Hi,
You can see [this action](https://github.com/nvda-es/TeleNVDA/blob/teleNVDA/.github/workflows/upload-on-tag.yaml) as an example on how to automate including the changelog in the release body.

**Comment by Arfs6** [comment]
Hi Manuel, don't worry, I am less busy (for now).

Here is what I've done:

1. Edited `src/write_version_data.py` to write the version to a file "version.txt". The workflow uses this for naming releases and artifacts.
2. Edited `scripts/build.ps1` to run `src/write_version_data.py`.
3. Edited `.github/workflows/release.yml`:
    - Enabled manual triggering of workflow.
    - Changed push trigger from next-gen to `release` tag.
    - Implemented zipping the dist directory that is generated by building TWBlue binary, and added it to the list of release assets.
    - I learnt nsis is installed by default, so I dropped the step that installs it.
4. Added `version.txt` to `.gitignore` file.

### Notes

1. You said:

    > Do you think you could change it so it generates a release whenever we push new tags to next-gen?

    Is it possible to push tag to a branch? And, what type of tag should trigger this? The current state is, when the workflow is manually triggered, it will create a release on `v<version_number>` tag. Another way the workflow gets triggered, is by a push to the release tag, I have no idea what that means. So, please implement it :)
2. The newly generated release has a general and vague note. A list of new features / bug fixes is supposed to be the note.
3. I am in support of creating a github page for TWBlue, but I think the domain should be changed. Something like twblue.io.

**Comment by manuelcortez** [comment]
No problem. I'll merge this now and will include release on tags. Thank you very much for your efforts! It looks really super awesome.

**Comment by Arfs6** [comment]
You're welcome :) I'd check your implementation when you push :)

**Comment by manuelcortez** [comment]
No problem. In fact it's just a matter of replace "release" for v20* on the pattern for release. See more at https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags. That should be enough for our needs, at least according to other projects (for now closed source ones, sadly) I am implementing this way.

**Comment by Arfs6** [comment]
So, are you going to figure out the version from gitlab before creating the tag?

**Comment by manuelcortez** [comment]
No. I'll push a tag named v2023.12.28 for example, and will let the tag to mark the release. I'll also adapt the code so we rely only in github's repo (this repo) as opposed to GitLab.

**Pull request merged**
