### PR TITLE
string cleanup

### PR DESCRIPTION
**Pull request by codeofdusk**
Cleaned up documentation.

### CODE REVIEW

**Comment by sukiletxe** [comment]
You've spotted some things that went unnoticed by me. Thank you for 
that. However, I would like to comment on some of your changes:
- application.name: I removed this because in Basque suffixes are used 
  to mark the case of the nouns (possesions for example), and I didn't 
  want to use hiphens all throughout the documentation to separate the 
  string and the suffix. I will consider changing "TWBlue" for "the 
  program" in some places, though (except definitely in the first heading).
- Favourites / favorites and authorize / authorise: Both forms are 
  correct, the first being US and the second UK.
- "updated by Bill Dengler and Sukil Etxenike": I didn't know you added 
  parts to the documentation. Can you specify what you added?

Thank you.

**Comment by codeofdusk** [comment]
I made corrections to the docs.

The application uses “authorize” and “favorite” because I corrected those forms in the main app.

**Comment by sukiletxe** [comment]
I reiterate: using "favorite" and "authorize" instead of "favourite" and 
"authorise" is just using American spelling, not correcting. Both 
spellings are accepted, according to wordreference. For now, we'll stick 
to the British spelling, as this was the spelling used before.
As for the credits section, if you say you have just corrected it, which 
certainly is right since you've corrected some mistakes which went 
unnoticed, you'll be listed in the "valuable corrections".
Thanks again for your corrections.

**Comment by codeofdusk** [comment]
Yes, but now the spellings between the program and documentation are inconsistent.

Bill

**Comment by sukiletxe** [comment]
I know. However, I think that the majority of spellings in TWBlue 
remains BR.

**Comment by sukiletxe** [comment]
in c464af83c2bb80fb6b441943005184c1caaf93b9 I've incorporated some of your changes. I've corrected the mistakes pointed out, and some whitespace issues too. For the fix for application.py, @manuelcortez should be the one who decides if using aplication.url is necessary.

**Comment by codeofdusk** [comment]
Close this, it's old.

**Pull request closed without merging**
