### PR TITLE
English cleanup

### PR DESCRIPTION
**Pull request by codeofdusk**
Cleaned up the project readme and the soundnotes

### CODE REVIEW

**Comment by sukiletxe** [comment]
Please, could you rebase in interactive mode (git rebase -i), join 
commits 1, 2 and 3 together, and 4 and 6 too (in another set, of 
course), and get rid of comit 5?
All this is explained in the documentation of git rebase (git help 
rebase). Note also that since you will be rewriting history, you will 
need to force-push after rebasing.
The reason I'm asking is because those commits are related to each 
other. And the reason for the deletion of commit 5 is because it doesn't 
seem to fit in this pr. Please open a separate one with that change.
Thanks!

**Comment by codeofdusk** [comment]
Done (on my fork), how do I update the pull request?

Thanks,
Bill

**Comment by sukiletxe** [comment]
It's alreadhy updated. But you still could join the first two, as they 
serve the same purpose. Thanks for your work.

**Comment by codeofdusk** [comment]
Done.

Bill

**Comment by codeofdusk** [comment]
I never knew about that command. Thanks for the tip!

**Pull request merged**
