### PR TITLE
Mastodon Support

### LINKED ISSUE #330: Mastodon/fediverse support.
With Twitter blocking OpenTween, I'd like the program to have support for the Mastodon universe. The gitHub is below. I'd love it if TW Blue could support at least some part of the Fediverse.

https://github.com/tootsuite/mastodon

### PR DESCRIPTION
**Pull request by manuelcortez**
This is an attempt to add support for Mastodon (and probably other networks that could speak the Activity Pub protocol) into TWBlue. I have made several attempts to add this in the past, although the amount of work required to make it possible is not trivial at all. Here I will list the progress of the support.

## Tasks to do

These are the most basic tasks TWBlue should be able to perform before this would be considered to be merged:

### Application

* [x] User authorisation.
    * [x] Error handling.
* [x] Create account in TWBlue.

### buffers

* [x] Home: Shows user's home timeline.
* [x] Local: shows instance's timeline.
* [x] federated: Shows public timeline across all instances.
* [x] Mentions
* [x] conversation list: Shows conversations (private toots which can be seen only by mentionned people).
* [x] conversation buffers: for every item in conversations list, displays every toot in the thread. This kind of buffers might be also be created from public toots.
* [x] sent toots.
* [x] Favorites.
* [x] bookmarks
* [x] Followers.
* [x] Following
* [x] Muted users.
* [x] blocked users.
* [ ] toot searches
* [x] user searches
* [x] User timelines
* [x] User followers
* [x] user friends
* [ ] List timelines
* [ ] Notifications.
* [x] Support for the Streaming API (only a small subset of all methods will be implemented).

### toots

* [x] toots are rendered via templates in invisible interface.
* [x] create toots:
    * [x] thread support.
    * [x] Attachments (images, videos, gifvs).
    * [x] Add content warnings.
    * [x] polls.
    * [x] Audio attachments.
* [x] Replies to one or multiple users.
* [x] Generate private toots (conversations).
* [x] Boost.
* [x] add/remove from favorites.
* [x] Add/remove from bookmarks.
* [x] Open toot and view stats
* [ ] Participate in polls.
* [ ] View poll results.
* [x] copy item to clipboard.
* [x] Repeat item.
* [x] Open in browser.
* [x] play audio or video.
* [ ] OCR Image.

### Users

* [x] Implement user actions (follow, unfollow, mute, unmute, block, unblock).
* [ ] View user profiles.
* [ ] Update profile.

### CODE REVIEW

**Comment by trypsynth** [comment]
Ooh, this looks epic. About to test. Thanks for all your work on this!

**Comment by Mohamed00** [comment]
Hi, I have a suggestion. I think the shortcut for followers in the Mastodon user timeline dialog should be changed to alt+l, because alt+o conflicts with the shortcut for the OK button.

**Comment by manuelcortez** [comment]
I'll do that, thanks for the suggestion!

**Comment by Mohamed00** [comment]
Hi, here are some more bugs I've noticed in the Mastodon support.
* Sometimes, it's impossible to destroy a search buffer.
STR:
1. Search for a user, example: twblue@maaw.social.
2. Try to destroy that buffer with alt+win+shift+i, or your equivalent shortcut in the invisible interface.

Expected: the buffer should be destroyed.
Actual: TWBlue says that the buffer is not a timeline and can't be deleted.
* Opening a user's timeline only works from home, not from all other buffers like it does in Twitter.

**Comment by trypsynth** [comment]
Hi, one problem I found is that you don't seem to fetch visibility options from instances. For example, hometown has a local_only option, but TWBlue doesn't support it

**Comment by masonasons** [comment]
This is because local only on hometown instances is accessed via an emoji, not a visibility setting.

**Comment by Mohamed00** [comment]
Hi, another bug. I noticed that if the user actions dialog is opened on a user who's on the same instance as you, it doesn't add the current instance to the end of the user's handle, which seems to create unpredictable results as Mastodon tries to search for the best match. I noticed this when I was attempting to follow someone on my instance, and briefly ended up following somebody else on a completely different server.

**Comment by masonasons** [comment]
Oh dear, please, please tell me you're not using account search to follow users... Please tell me you're not... Update to mastodon.py 1.7.0 and use account lookups or something but not, not that...

**Pull request merged**
