### PR TITLE
Update Twython to 3.5.0.

### PR DESCRIPTION
**Pull request by codeofdusk**

### CODE REVIEW

**Comment by jmdaweb** [comment]
We have to check this pull request carefully, we made custom changes to Twython.

Regards.


El 08/07/2017 a las 9:07, Bill Dengler escribió:
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/manuelcortez/TWBlue/pull/146

Commit Summary

  *   Update Twython to 3.5.0.

File Changes

  *   M src/twython/__init__.py<https://github.com/manuelcortez/TWBlue/pull/146/files#diff-0> (2)
  *   M src/twython/api.py<https://github.com/manuelcortez/TWBlue/pull/146/files#diff-1> (81)
  *   M src/twython/endpoints.py<https://github.com/manuelcortez/TWBlue/pull/146/files#diff-2> (61)

Patch Links:

  *   https://github.com/manuelcortez/TWBlue/pull/146.patch
  *   https://github.com/manuelcortez/TWBlue/pull/146.diff

**Comment by codeofdusk** [comment]
What custom changes?

Bill

**Comment by jmdaweb** [comment]
For example, image descriptions. @manuelcortez will tell us more.

El 08/07/2017 a las 10:10, Bill Dengler escribió:
What custom changes?

Bill

**Comment by codeofdusk** [comment]
We should contribute our changes upstream; it helps the libraries we use and makes updates easier.

**Comment by codeofdusk** [comment]
Any updates on this one?

**Comment by codeofdusk** [comment]
No response, so closing.

**Pull request closed without merging**
