### PR TITLE
croatian localization

### PR DESCRIPTION
**Pull request by zstanecic**

### CODE REVIEW

**Comment by manuelcortez** [comment]
There are some related bugs in the logger module and, unfortunately, in arrow too. I can't include the Croatian locale until we've fixed the arrow bugs. I've fixed the logger bugs and I'll make a commit to push them, but we need to create a new class in arrow (the package for date representation) for the croatian language. So I don't know nothing about croatian. If you can create a class and include it in the fixes/fix_arrow.py, it would be appreciated and I could include your translation in the next snapshot. You can use the three classes defined in the file as an example, or search the location of the arrow package, and take a look at the locales.py file. If you don't know python or are unsure about creating new classes, I could do it, but I'd need your help.

**Comment by zstanecic** [comment]
hi, i cannot do it cause i don't know python

W dniu 2015-03-17 o 02:06, Manuel Cortéz pisze:

**Comment by manuelcortez** [comment]
I've uploaded a simple file where I copied some of the code for the english locale in arrow. If you have a chance, please take a look in the file and try to change the strings for croatian equivalents. I've written some comments (a comment line in python starts with a # symbol) for helping you in understanding some format things. If you modify the file don't delete the '' symbols.

**Comment by manuelcortez** [comment]
Oh, this thing does not support upload for python files, only images. So I'll put below the contents for the file.

**\* start of the python file***
    # Here, {0} can be a minute, a second, an hour, etc.
    past = '{0} ago'
    future = 'in {0}'

```
# here, {0} can be a number, for example in minutes, {0} can be 5 minutes, 10 minutes, etc.
timeframes = {
    'now': 'just now',
    'seconds': 'seconds',
    'minute': 'a minute',
    'minutes': '{0} minutes',
    'hour': 'an hour',
    'hours': '{0} hours',
    'day': 'a day',
    'days': '{0} days',
    'month': 'a month',
    'months': '{0} months',
    'year': 'a year',
    'years': '{0} years',
}

# If meridians for croatian are the same than for English please don't modify them.
meridians = {
    'am': 'am',
    'pm': 'pm',
    'AM': 'AM',
    'PM': 'PM',
}

month_names = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July',
    'August', 'September', 'October', 'November', 'December']
month_abbreviations = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug',
    'Sep', 'Oct', 'Nov', 'Dec']

day_names = ['', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
day_abbreviations = ['', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
```

**\* end***

**Pull request merged**
